### ISSUE TITLE
Welcome to ngrok!

### ISSUE THREAD

**Issue by miguelangelhernandd** [ultrasecurity/Storm-Breaker#100]
someone else happens to it, install the tool and it always takes me to the same page someone else happens to it.

 Before you can serve HTML content, you must sign up for an ngrok account and install your authtoken.
I already have an account, why am I seeing this page?
Make sure that you Install Your Authtoken and then restart the ngrok agent.

**Comment by hasharmujahid** [comment]
Same Here!

**Comment by fellixix** [comment]
pls has anyone find a solution to this im also having the same problem

**Comment by Monjurul-Hasan-Sohan** [comment]
same here too

**Comment by s-kaito77** [comment]
After signin  to ngrok and get your **authtoken**, copy it and do this command if you have ngroke installed
 `./ngrok authtoken 24Yq....etc`
 the solution is to use 

> **sudo**

 before  the above command
 
so the final command will be :
`sudo ./ngrok authtoken 24Yq....`

**Comment by tweleveangrymen1** [comment]
> so the final command will be : `sudo ./ngrok authtoken 24Yq....`

it worked for me

**Comment by JMichael55** [comment]
this didn't work for me when used sudo ./ngrok authtoken with my token it just says sudo: ./ngrok: command not found
