### ISSUE TITLE
Webcam images are black

### ISSUE THREAD

**Issue by ghost** [ultrasecurity/Storm-Breaker#107]
So I have been using Storm-Breaker, and when using the webcam, everything works fine but the retrieved images are black. I have a few interesting ideas where it might have escalated. 

I think it might be my phone's OS which is different from android, it is Xi aomi which uses MIUI.

But I am still not sure. 

Thanks in advance!

**Comment by Occaamy** [comment]
I happen to have the same problem.

If i test it on my phone ( uses MIUI ; if this information is of any use) the images can be viewed. But for all the other images captured from other devices the images are black.

**Comment by wizhardhacker1** [comment]
any fix for this?
