### ISSUE TITLE
Cant install 

### ISSUE THREAD

**Issue by yhoungdev** [ultrasecurity/Storm-Breaker#108]
/usr/bin/python3: No module named pip

**Comment by TUSONE** [comment]
apt-get install python3-pip

**Comment by yhoungdev** [comment]
It still same issue 

![Uploading 155627991...]![image](https://user-images.githubusercontent.com/54102389/155627992-22cf6d29-246e-4aeb-bab6-ba65ae5c0e8f.jpeg)

**Comment by NandaKishan** [comment]
you first  have to install the requirments, so use `python3 -m install -r requirments.txt`, this will install pyngrok and neofetch and all the required files and the you can use `python3 Storm-Breaker.py`

**Comment by Sankar143388** [comment]
> It still same issue
> 
> ![Uploading 155627991...]![image](https://user-images.githubusercontent.com/54102389/155627992-22cf6d29-246e-4aeb-bab6-ba65ae5c0e8f.jpeg)



call me 81900143389
