### ISSUE TITLE
Storm-Breaker-Ngrok

### ISSUE THREAD

**Issue by AsadMahmood123** [ultrasecurity/Storm-Breaker#11]
![Screenshot_2021-06-10_15_59_45](https://user-images.githubusercontent.com/46080631/121549010-7ac9d300-c9db-11eb-915b-d6eec66f6009.png)
Error is shown in the screenshot above, I have pasted my ngrok token in config.json file, and even i have pasted the ngrok file in the directory, But still it is showing this error

**Comment by Steam-21-lol** [comment]
u have to be on bridged mode

**Comment by AsadMahmood123** [comment]
Thanks for the response in a very short time ....
