### ISSUE TITLE
ngrok brings me to sign in page none of the solutions work

### ISSUE THREAD

**Issue by JMichael55** [ultrasecurity/Storm-Breaker#115]
I use cd Storm-Breaker then sudo su then ngrok (my token) an it just says a bunch of stuff about commands and stuff but at the bottom says ERROR:  Unrecognized command: 25nSNc7wvlWVLQna3HXTsWcBrgQ_4Ag6511AMNEbU6LCLfmDb

**Comment by kairavxd** [comment]
same

**Comment by Ajkonek** [comment]
$ sudo authtoken "your token".
