### ISSUE TITLE
Could not found the ngrok module after successful installation

### ISSUE THREAD

**Issue by semer-11** [ultrasecurity/Storm-Breaker#117]
Traceback (most recent call last):
  File "Storm-Breaker.py", line 7, in <module>
    from modules import localhost
  File "/test/Storm-Breaker/modules/localhost.py", line 1, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'

**Comment by Abc123hacks** [comment]
Just copy the pyngrok folder from /home/username/.local/lib/python3.9/site-packages/ and paste it in the Storm-Breaker folder now run "sudo python3 Storm-Breaker.py" and you are good to go!

**Comment by cyberpsychooo** [comment]
it works
