### ISSUE TITLE
ModuleNotFoundError:  No module named "pyngrok"

### ISSUE THREAD

**Issue by Gab750** [ultrasecurity/Storm-Breaker#12]
![stormbreaker](https://user-images.githubusercontent.com/81226515/121772015-9370ef00-cb7b-11eb-9fd0-34e7aaae07c2.png)

**Comment by Moejay90** [comment]
same here, did you get it resolved?

**Comment by Gab750** [comment]
> same here, did you get it resolved?

Nope

**Comment by santhoshsandu** [comment]
solution 
sudo su
cd Storm-Breaker
virtual venv
source venv/bin/activate
pip3 install pyngrok

**Comment by Gab750** [comment]
> cd Storm-Breaker
When i type "virtual venv" it says Command 'virtual' not found, did you mean:
  command 'virtaal' from deb virtaal
Try: apt install <deb name>

**Comment by Wasiq00** [comment]
same problem
ModuleNotFoundError: No module named 'pyngrok'

**Comment by PRUSO-MAOU** [comment]
Try this virtualenv

**Comment by KitsuneJoker** [comment]
@santhoshsandu 
I try to use your solution

sudo su
cd Storm-Breaker
virtualenv venv
source venv/bin/activate
pip3 install pyngrok

But there will still be errors
ModuleNotFoundError: No module named 'pyngrok'

**Comment by PRUSO-MAOU** [comment]
Try this please 

Sudo pip3 install pyngrok

**Comment by KitsuneJoker** [comment]
@PRUSO-MAOU
  thanks

**Comment by PRUSO-MAOU** [comment]
Did it work?

**Comment by KitsuneJoker** [comment]
yes，it works

**Comment by KitsuneJoker** [comment]
@PRUSO-MAOU 
Excuse me, I have another question, when the program is running it will download ngrok, but I have downloaded ngrok before, is this normal?

**Comment by PRUSO-MAOU** [comment]
I don't know bro .iam also new to this stuff

**Comment by Anonymous101404** [comment]
i just used "sudo pip install pyngrok" Then it worked

**Comment by riyazshaik95** [comment]
just uninstall everything and clone it again 
git clone **********
cd storm-breaker
sudo bash install.py
sudo -p pip -r  requirments.txt
sudo pip install pyngrok
 and then it works if you face same issue uninstall again and follow the above code

**Comment by JadeXenpai** [comment]
> Try this please
> 
> Sudo pip3 install pyngrok

It works

**Comment by suganth345** [comment]
Installing the requirments again, will resolve this error

**Comment by ryhankabir562** [comment]
> ![stormbreaker](https://user-images.githubusercontent.com/81226515/121772015-9370ef00-cb7b-11eb-9fd0-34e7aaae07c2.png)

$ git clone https://github.com/ultrasecurity/Storm-Breaker
$ cd Storm-Breaker
$ sudo su
$ sudo bash install.sh
$ python3 -m pip install -r requirments.txt
$ sudo python3 Storm-Breaker.py

**Comment by ryhankabir562** [comment]
> ![stormbreaker](https://user-images.githubusercontent.com/81226515/121772015-9370ef00-cb7b-11eb-9fd0-34e7aaae07c2.png)

$ git clone https://github.com/ultrasecurity/Storm-Breaker
$ cd Storm-Breaker
$ sudo su
$ sudo bash install.sh
$ python3 -m pip install -r requirments.txt
$ sudo python3 Storm-Breaker.py

> Installing the requirments again, will resolve this error



> ![stormbreaker](https://user-images.githubusercontent.com/81226515/121772015-9370ef00-cb7b-11eb-9fd0-34e7aaae07c2.png)

$ git clone https://github.com/ultrasecurity/Storm-Breaker
$ cd Storm-Breaker
$ sudo su
$ sudo bash install.sh
$ python3 -m pip install -r requirments.txt
$ sudo python3 Storm-Breaker.py

**Comment by DineshVC** [comment]
![16492842195663268721310648379783](https://user-images.githubusercontent.com/102571753/162083094-7292fae4-07a2-40df-9e06-45221d92b75a.jpg)

Unable to install pyngrok

**Comment by vijaycaimi** [comment]
I got below error: 

[ERROR] pyngrok not found
[INFO] Run pip3 install -r requirements.txt

then i install pip3 :  sudo apt install python3-pip
then run :  pip3 install -r requirements.txt  
that it

**Comment by BottleCap88** [comment]
Please Run NGROK On Port **** AND send Link To Target > ngrok http ****


What should I do ?

**Comment by Geo20202** [comment]
the same problem i cant

**Comment by aso00000** [comment]
> Try this please
> 
> Sudo pip3 install pyngrok

sorry, how do i download it? do i add a new code and type this? i tried it this way but i still get the same error
