### ISSUE TITLE
Android phone "This page isn't working" after opening link

### ISSUE THREAD

**Issue by SgtFoose** [ultrasecurity/Storm-Breaker#121]
(Nokia 6.1 TA-1043 Android 10 build 00WW_415C_SP11):
Result after opening the link on Firefox:
Not found
Tunnel 440-%%%-$-@@@.ngrok.io not found
ERR_NGROK-3200 

Link does work when opening on the Kali VM.

Running Storm-Breaker on WM Ware workstation Kali
Network setup as NAT (share host IP address)

**Comment by SgtFoose** [comment]
UPDATE:
My Kali is running on a VM and Network set to NAT. This prevents the server to have access to the www.
I connected my wifi dongle to my Kali VM and made a wifi connection to my router. After that the link works and stuff like webcam works perfect! TinyURL your link to make it better! One thing is the target needs to allow webcam access which they most likely won't allow! Can we modify the picture/portal to make it more attractive to accept? I was thinking about making it say "click here to add funny emoticons to your selfie for free!"?

**Comment by 34435563424** [comment]
help me when i change my vms network adaptor from nat network to my pcs' wifi card ,the wifi in my kali vm doesnt work
