### ISSUE TITLE
python3: can't open file '/root/Desktop/Storm-Breaker/Storm-Breaker': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by r7nj7** [ultrasecurity/Storm-Breaker#123]
what i have to do whit this problem

**Comment by Dayush82** [comment]
/usr/bin/python3: No module named pip im having this problem what should i do?

**Comment by dhruvin7545** [comment]
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by deeq21** [comment]
Hello I'm having the same issue with starting Stormbreaker with the following command python3 Storm-Breaker.py

**Comment by GeminiSource** [comment]
I think maybe you should try:    python3 st.py     I think...look for a .py file that under a different name.....It could have juist been renamed?

**Comment by fletch505** [comment]
1 sudo apt-get install simplescreenrecoder
2  git clone https://github.com/ultrasecurity/Storm-Breaker
3   $ cd Storm-Breaker
4 $ sudo bash install.sh
5 python3 st.py  -m pip install -r requirements.txt   

And that should do it i had the same thing come up but #5 was the line that got me in
