### ISSUE TITLE
Need help with Storm Breaker. On Mac!

### ISSUE THREAD

**Issue by Skye12345-Emma** [ultrasecurity/Storm-Breaker#127]
(base) Skye:~ macbookpro$ sudo apt install neofetch
Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk1.8.0_321.jdk/Contents/Home/bin/apt" (-1). Got that when doing and trying out everything?

**Comment by UMAPATHYY** [comment]
> (base) Skye:~ macbookpro$ sudo apt install neofetch Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk1.8.0_321.jdk/Contents/Home/bin/apt" (-1). Got that when doing and trying out everything?

same error

**Comment by uidops** [comment]
why are you trying to install neofetch with apt in macos? package manager of macos isn't apt
