### ISSUE TITLE
No superuser binary detected. Are you rooted?

### ISSUE THREAD

**Issue by jordnhk** [ultrasecurity/Storm-Breaker#13]
Can i use the tool in termux?

**Comment by Faiz-Anjum** [comment]
You can probably use it if you install the right dependencies in the right environment. However 

> No superuser binary detected. Are you rooted?

suggests that your phone is not rooted or you haven't granted super user permission to Termux.

**Comment by Kirito717** [comment]
> 
My device is not rooted
How do I give Termux super user??
