### ISSUE TITLE
WARNING: Running pip as the 'root' user 

### ISSUE THREAD

**Issue by dhruvin7545** [ultrasecurity/Storm-Breaker#142]
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by blockcrafter21** [comment]
well
just run pip without sudo

**Comment by 324569375** [comment]
> well just run pip without sudo

This is an error when running sudo bash install.sh, without root permission, he will say Please, run as root!
