### ISSUE TITLE
webcam captures images all are black.

### ISSUE THREAD

**Issue by drixmat** [ultrasecurity/Storm-Breaker#143]
it captures the image and save it in image folder but all image are black
![280155733_519022253200412_7396984069217831388_n](https://user-images.githubusercontent.com/104344237/167083906-4b68cab5-8bf8-40fc-a53e-8f6a841be365.jpg)

**Comment by DarkAngel5336** [comment]
YES BRO SAME PROBLEM......DID U FIND THE SOLUTION
