### ISSUE TITLE
ngrok not running or link is not displayed

### ISSUE THREAD

**Issue by ShivaKrishna2003** [ultrasecurity/Storm-Breaker#144]
it shows 
Please Run NGROK On Port 8180 And send Link to Target
-- but I have my ngrok running on the port it is not showing which link to forward

**Comment by meepmaster360** [comment]
ngrok http 8180

**Comment by LluisAguilar** [comment]
You have tu run this command in your terminal `ngrok http 8180`, make sure you have [Ngrok ](https://ngrok.com/download) installed

**Comment by Atasharef1381** [comment]
please uninstall `ngrok` and then install it again
