### ISSUE TITLE
i already captured an images, but i can't see any images in the folder.

### ISSUE THREAD

**Issue by JohnPastorall0997** [ultrasecurity/Storm-Breaker#145]
![image](https://user-images.githubusercontent.com/104306469/167386948-9e8b42f6-17a6-4f57-b21d-1d97b6668968.png)

![image](https://user-images.githubusercontent.com/104306469/167387023-0e900c57-72a6-4c17-a93e-1b43294c4709.png)

can anyone help me out? thank you!

**Comment by ShivaKrishna2003** [comment]
the directory u opened doesnt look same. you are looking in Storm-Breaker_main, but the images are in Storm-Breaker directory 
there must be another file named "Storm-Breaker" look if u can find. open file system folder and look in it

**Comment by JohnPastorall0997** [comment]
> the directory u opened doesnt look same. you are looking in Storm-Breaker_main, but the images are in Storm-Breaker directory there must be another file named "Storm-Breaker" look if u can find. open file system folder and look in it

thankyouuu i will try to find it

**Comment by Atasharef1381** [comment]
If your problem is solved , We Would Appreciate if you give Stars for further developments !

**Comment by Atasharef1381** [comment]
If your problem is solved , We Would Appreciate if you give Stars for further developments !
