### ISSUE TITLE
Installing stuck at 99%

### ISSUE THREAD

**Issue by Dibess** [ultrasecurity/Storm-Breaker#147]
Installing sudo bash install.bsh is stuck at 99%
![kali](https://user-images.githubusercontent.com/105547892/168428927-eb44e3a3-3784-425f-9fbc-adc26c5785a8.JPG)

**Comment by Atasharef1381** [comment]
have you tried installing with vpn ?

**Comment by Jamila25122512** [comment]
Hi
what is [sudo] passxord of kali
Can you help me

**Comment by Atasharef1381** [comment]
There is a password you set for wsl the first time you're installing it .
It is different for every system

**Comment by Jamila25122512** [comment]
How can I get this password and where?

**Comment by Jamila25122512** [comment]
Do you help me please
