### ISSUE TITLE
Storm breaker only generate localhost link

### ISSUE THREAD

**Issue by LluisAguilar** [ultrasecurity/Storm-Breaker#152]
I have seen other tutorials and when you use `storm breaker` and choose one of the 4 first options it should generate two links, one for localhost and another link that is global. Is there a reason for why I only get localhost link?

![ss-stormB](https://user-images.githubusercontent.com/36077886/169431273-da1a8121-2b7b-4d87-8cab-a81a4acef697.png)

**Comment by ayushis2ayush** [comment]
you can port forward it with the cloudflare or ngrok

**Comment by Atasharef1381** [comment]
If You pay attention , first you must run that link and then port forward it . Thanks A million .

We Would Appreciate if you give Stars for further developments !

**Comment by snowleoparddd17** [comment]
> you can port forward it with the cloudflare or ngrok

how would i do it with ngrok?

**Comment by Mrkingnevergetsout** [comment]
That's not a big deal you can search for any website which can change it paste that link there and boom you got your required link

**Comment by ivano1981** [comment]
you can take http link from ngrok page forwarding
