### ISSUE TITLE
Need a help with the installation process

### ISSUE THREAD

**Issue by Treng123** [ultrasecurity/Storm-Breaker#153]
Hey guys. Im new here with these coding and Linux. I tried to install Storm Breaker by watching some YouTube tutorials. But after I hit enter the link it says “Unable to install Storm Breaker”. Do you know the reason? Am I missing some requirements?  I did download and using CamPhish tool yesterday and its working. Please help. Thanks

**Comment by joshkar** [comment]
Hello. Please send us your distribution name to review ❤️👌

**Comment by Atasharef1381** [comment]
Please use vpn while installing and if you're on windows try using `git clone https://github.com/ultrasecurity/Storm-Breaker.git` . it should install then for you !
