### ISSUE TITLE
Please Run NGROK On Port 2627 AND Send Link To Target > ngrok http 2627 

### ISSUE THREAD

**Issue by Tarek42x** [ultrasecurity/Storm-Breaker#157]
when i try to access webcam  he ask me to run negrok  on port 2627 any help here

**Comment by waefedfg** [comment]
Same here when ever I use it and my friends click on the site it says cannot reach site. (This propably has something to do with run ngrok on port 2627)

**Comment by Scopethewolf** [comment]
same here

**Comment by snowleoparddd17** [comment]
same here...

**Comment by snowleoparddd17** [comment]
> you need to type ./ngrok http numbers

i tried that 3 times in 3 different places and didnt work 

place 1 right after i get that message inside stormbreaker
place 2 in the terminal with cd storm-breaker
place 3 in the regular terminal without a cd

any help with where exactly to type that?

**Comment by snowleoparddd17** [comment]
> you need to type ./ngrok http numbers

this is the only response i get, if i do it with cd Storm-Breaker. yet after this it still doesnt fix the issue before using access webcam


![2022-07-16](https://user-images.githubusercontent.com/108897162/179274764-938c7072-f799-47bd-9316-826a98ef4c2c.png)

**Comment by KaliPrototype** [comment]
Create an terminal and do the following : 

sudo -i 
ngrok http 2627 
After that, copy the http/https link and send it to the victim.

**Comment by tieego** [comment]
same problem here?

**Comment by Nkuta** [comment]
So far I've only been able to generate local host links, which when sent to the trial device appear as plain text even though they contain the letters "http"

**Comment by AndresSanchezAlbertti** [comment]
I have a problem when i send the https link, i get a login page, wich credentials may i use?

**Comment by Maha3567rg** [comment]
But it worked for me really
