### ISSUE TITLE
Failed to establish a new connection

### ISSUE THREAD

**Issue by shown19** [ultrasecurity/Storm-Breaker#159]
Hello, may I know the solution for this issue?

![err1](https://user-images.githubusercontent.com/10029400/170698483-a54ad507-c4a1-4c0d-a747-20790984bee6.JPG)

**Comment by arduino-man** [comment]
This is a problem with your virtual machine networking 100% you don't have proper DNS resolution.

**Comment by ethicalhacker7192** [comment]
did you check if your internet has a pi hole(raspberry pi that blocks ads), that was the problem with mine. also check your virtual machine(if you are using a virtual machine), if your virtual machine network is not working, that is the problem.

**Comment by BROKENIGG** [comment]
> networking

How do i solve, pls help ;-;

**Comment by BROKENIGG** [comment]
Someone pls help;-;

**Comment by ethicalhacker7192** [comment]
To: BROKENIGG
I can help just tell me what the problem is.

**Comment by BROKENIGG** [comment]
> 

its showing just like this
![Screenshot 2022-07-03 215146](https://user-images.githubusercontent.com/108614741/177048491-55224f04-987a-493e-8729-269d19d752ac.png)
![Screenshot 2022-07-03 215257](https://user-images.githubusercontent.com/108614741/177048494-82f628f4-8005-4fed-a4be-536651b895e5.png)
, everything went fine till sudo python3 st.py command, i'm learning how to use kali linux past 3 days

**Comment by ethicalhacker7192** [comment]
> > 
> 
> its showing just like this ![Screenshot 2022-07-03 215146](https://user-images.githubusercontent.com/108614741/177048491-55224f04-987a-493e-8729-269d19d752ac.png) ![Screenshot 2022-07-03 215257](https://user-images.githubusercontent.com/108614741/177048494-82f628f4-8005-4fed-a4be-536651b895e5.png) , everything went fine till sudo python3 st.py command, i'm learning how to use kali linux past 3 days

Have you missed a line, all of kali linux runs from Debian linux, if you have missed a line here is the installation: $ git clone https://github.com/ultrasecurity/Storm-Breaker
 $ cd Storm-Breaker
 $ sudo bash install.sh 
$ sudo python3 -m pip install -r requirements.txt $ sudo python3 st.py
Remember to get rid of the $ signs at the beginning. If that did not work check your pip installer, ngrok, php, neofetch, python3, and git. Also check if your internet is interfering.
