### ISSUE TITLE
I dont know how to update (i am a noob in hacking sorry)

### ISSUE THREAD

**Issue by darkkillerking** [ultrasecurity/Storm-Breaker#160]
sudo python3 st.py
Please Update Tools 

i have this problem.
but i dont know how to fix it.
plss help

**Comment by Peppe289** [comment]
bro, you have been literally told. the tool needs to be updated. if you don't know how to use git commands, download this repository again.

the python code checks if you are using the latest version of this tool:
https://github.com/ultrasecurity/Storm-Breaker/blob/a1f9926cd6ec0717094d47ce9bdf140c3f0b61d9/module/check.py#L70

in case the [Settings.json online](https://raw.githubusercontent.com/ultrasecurity/Storm-Breaker/main/Settings.json) file has a larger value in "version" give the message and close

https://github.com/ultrasecurity/Storm-Breaker/blob/a1f9926cd6ec0717094d47ce9bdf140c3f0b61d9/module/check.py#L71

**Comment by darkkillerking** [comment]
What do i need to type in the terminal 
because i dont know what to type?
i am noob thats why i am asking
plsss answer

**Comment by Mrpolack** [comment]
You just have to delete the project folder and dowloand again the entire repo. Maybe before that you have to run:

sudo apt-get update && sudo apt-get upgrade
