### ISSUE TITLE
Errno 111 Connection refused

### ISSUE THREAD

**Issue by ethicalhacker7192** [ultrasecurity/Storm-Breaker#165]
Every time I try to open the st.py with python3, this message pops up. The sad thing is that it was working for a while, then this happened! I really need help, I tried deleting everything and then reinstalling including python3, pip, ngrok, and everything else.
> ![Screenshot_2022-06-19_01_55_56](https://user-images.githubusercontent.com/107788660/174471441-d4f32001-64be-4025-9884-af4fcff15e45.png)

**Comment by ethicalhacker7192** [comment]
the problem was that my pihole was blocking it

**Comment by bhairavghanta** [comment]
> the problem was that my pihole was blocking it

How to resolve this issue

> Every time I try to open the st.py with python3, this message pops up. The sad thing is that it was working for a while, then this happened! I really need help, I tried deleting everything and then reinstalling including python3, pip, ngrok, and everything else.
> 
> > ![Screenshot_2022-06-19_01_55_56](https://user-images.githubusercontent.com/107788660/174471441-d4f32001-64be-4025-9884-af4fcff15e45.png)

how to Resolve this issue?

**Comment by spyfox46** [comment]
i have same problems and i have no ideas or clues how to solve it

**Comment by Aryan2139** [comment]
> i have same problems and i have no ideas or clues how to solve it

Bro can you help me

**Comment by Aryan2139** [comment]
> > the problem was that my pihole was blocking it
> 
> How to resolve this issue
> 
> > Every time I try to open the st.py with python3, this message pops up. The sad thing is that it was working for a while, then this happened! I really need help, I tried deleting everything and then reinstalling including python3, pip, ngrok, and everything else.
> > > ![Screenshot_2022-06-19_01_55_56](https://user-images.githubusercontent.com/107788660/174471441-d4f32001-64be-4025-9884-af4fcff15e45.png)
> 
> how to Resolve this issue?

Bro can you help

**Comment by ethicalhacker7192** [comment]
Ngrok probably banned you, they banned me and the script stopped working.
