### ISSUE TITLE
ERR_NGROK_6022

### ISSUE THREAD

**Issue by omarakl** [ultrasecurity/Storm-Breaker#166]
whenever the "target" opens the link it shows the error page ...

**Comment by an0nym0us551** [comment]
hey did you ever find a solution for this error,???

**Comment by omarakl** [comment]
> hey did you ever find a solution for this error,???

Not yet 😅 Actually I forgot about it 😅

**Comment by j0j0karar** [comment]
me too :(

**Comment by omarakl** [comment]
I think, we should download the ngrok and that might fix the problem..
