### ISSUE TITLE
PASSWORD NEVER RECOVERED

### ISSUE THREAD

**Issue by 9993rills** [ultrasecurity/Storm-Breaker#17]
![Screenshot_2](https://user-images.githubusercontent.com/84611223/126148653-c4be59d8-a094-493f-a099-f8fecdfffb12.jpg)
Passwords not recovered....

**Comment by Atasharef1381** [comment]
have you tried it on other systems as well ?

**Comment by 9993rills** [comment]
> have you tried it on other systems as well ?

Windows 10 & 8
