### ISSUE TITLE
I KEEP GETTING PSUTIL ERROR MESSAGE PLZ HLP

### ISSUE THREAD

**Issue by cdfil** [ultrasecurity/Storm-Breaker#171]
RecursionError: maximum recursion depth exceeded in __subclasscheck__
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psutil
Failed to build psutil                                                       
ERROR: Could not build wheels for psutil, which is required to install pyproject.toml-based projects                                                      
An error occurred! seems pip doesn't work.

**Comment by HackerManChad** [comment]
I keep getting this as well, have you found a solution?
