### ISSUE TITLE
Use without ngrok?

### ISSUE THREAD

**Issue by ll3N1GmAll** [ultrasecurity/Storm-Breaker#179]
Can Storm-Breaker be used without ngrok? I want to disable ngrok for use with standard port forwarding.

**Comment by an0nym0us551** [comment]
I don't think so, wish you could tho

**Comment by Jasraj4325** [comment]
this will be done automatically just add this code to the repositories  add this <ultrasecurity/stormbreaker.py.run/.pip>

**Comment by ll3N1GmAll** [comment]
> this will be done automatically just add this code to the repositories add this <ultrasecurity/stormbreaker.py.run/.pip>

Thanks for your reply; but I do not understand your instructions. I don't see any file nor path named "stormbreaker.py.run".
