### ISSUE TITLE
colorama and module import issue in kali linux not executig Storm-Breaker

### ISSUE THREAD

**Issue by Autobot4123** [ultrasecurity/Storm-Breaker#18]
Traceback (most recent call last):
  File "/home/hunter/Storm-Breaker/Storm-Breaker.py", line 6, in <module>
    from modules import banner
  File "/home/hunter/Storm-Breaker/modules/banner.py", line 2, in <module>
    from colorama import Fore
ModuleNotFoundError: No module named 'colorama'
 
**THIS IS THE ISSUE IN THE CODE PLEASE SOLVE THE ISSUE ASAP AND HELP ME HOW TO FIX THE ISSUE**
@ultrasecurity

**Comment by HariKrishna100** [comment]
Yes pls help us with this issue we are stuck hence Linux-installer.sh command will not work pls check on that also it says no such directory found pls fix the issue asap
