### ISSUE TITLE
ERR_NGROK

### ISSUE THREAD

**Issue by umarahmad125** [ultrasecurity/Storm-Breaker#182]
![Screenshot_20220804-011205](https://user-images.githubusercontent.com/47673584/182700257-ea4e1c28-a83d-44cc-9d49-89849a5e7ee5.jpg)

**Comment by N00b-Teodore** [comment]
https://ngrok.com/docs/getting-started

This solved it for me.

**Comment by umarahmad125** [comment]
Already
But same error

**Comment by umarahmad125** [comment]
Not complete
