### ISSUE TITLE
Generated link not working properly

### ISSUE THREAD

**Issue by davenkix** [ultrasecurity/Storm-Breaker#190]
I was able to generate the link with ngrok, set everything up. When I open it (trying to access webcam) everything looks like it should, I even see the fake phone picture but there is no asking for webcam permission, so none of this will have effect as I can't get any images. Can anybody help me?

**Comment by munonzito** [comment]
Did you tried using the https link?

**Comment by munonzito** [comment]
Did you try using the https link?

**Comment by naren970** [comment]
I also faced same problem and not able to get any client info when client open the link
I used the https only
