### ISSUE TITLE
ERR_NGROK_6022

### ISSUE THREAD

**Issue by j0j0karar** [ultrasecurity/Storm-Breaker#194]
help me

**Comment by king888-glitch** [comment]
Same problem im doing everything right but it tell me ERR_NGROK_6022

**Comment by Dustie16** [comment]
same please help

**Comment by MrvKrt** [comment]
You should install your ngrok token. Plus, you must sign-up Ngrok.

For install token, visit Your Authtoken page in Ngrok account:

`ngrok config add-authtoken <token>`

**Comment by bmrs1** [comment]
After config token same error repeating
