### ISSUE TITLE
Can we edit the templates??

### ISSUE THREAD

**Issue by nobiDebian** [ultrasecurity/Storm-Breaker#199]
Can we edit the templates?? Html

**Comment by joshkar** [comment]
Yes, they can be edited. If you have knowledge in the field of html, css, js, you can


But if you are looking to add templates that by adding them. You can use the tool

We will post its training soon

Because the current version is customizable and expandable

**Comment by nobiDebian** [comment]
Thanks man nice work 👍 it helps me to prank my classmates 🤣

**Comment by joshkar** [comment]
This tool is not provided as a joke 🥲

Rather, it is for research purposes for people interested in cyber security

(Dimensions of social engineering on the browser platform)
