### ISSUE TITLE
Storm-Breaker home menu options do not appear

### ISSUE THREAD

**Issue by Git-JoaoPauloSantos** [ultrasecurity/Storm-Breaker#201]
Storm-Breaker's initial menu options do not appear, and after clicking on the link generated by ngrok, a login screen appears asking for username and password. Was this really supposed to happen?

Img initial menu: https://drive.google.com/file/d/1H5i3fU8Z3bceXvlGPRp3kovpg7gkB7x9/view?usp=sharing
Img login screen: https://drive.google.com/file/d/146IoKZWHfO1pI5al3C7Zo2kk1mxdspGh/view?usp=sharing

**Comment by WaelYasaki** [comment]
The same problem with me
Thank you, waiting the answer

**Comment by Lilpablo999** [comment]
all you need is to start ngrok/cloudflare on http://localhost:2525 then after that paste your link to your web browser, it will ask you for username and password then enter admin as user and pass you should find your link there to send to your target.

**Comment by WaelYasaki** [comment]
> all you need is to start ngrok/cloudflare on http://localhost:2525 then after that paste your link to your web browser, it will ask you for username and password then enter admin as user and pass you should find your link there to send to your target.

Thank you, it successes, But the link sent to the target doesn't work 
I tried to open it from chrome and firefox :/

**Comment by joshkar** [comment]
> Storm-Breaker's initial menu options do not appear, and after clicking on the link generated by ngrok, a login screen appears asking for username and password. Was this really supposed to happen?
> 
> Img initial menu: https://drive.google.com/file/d/1H5i3fU8Z3bceXvlGPRp3kovpg7gkB7x9/view?usp=sharing Img login screen: https://drive.google.com/file/d/146IoKZWHfO1pI5al3C7Zo2kk1mxdspGh/view?usp=sharing

Hello. When you send the link to the victim, do you expect him to enter your web panel easily?

Certainly not. For this reason, we have set a username and password for this section, and it is admin by default.

**Comment by joshkar** [comment]
> all you need is to start ngrok/cloudflare on http://localhost:2525 then after that paste your link to your web browser, it will ask you for username and password then enter admin as user and pass you should find your link there to send to your target.

no There is no need for this. Use ngrok only when you want to give the link to the victim

The hacker can simply raise his web panel on the local host and wait for the victim's information


Because we run ngrok so that a user who is outside our local network can access the desired template

**Comment by joshkar** [comment]
> > all you need is to start ngrok/cloudflare on http://localhost:2525 then after that paste your link to your web browser, it will ask you for username and password then enter admin as user and pass you should find your link there to send to your target.
> 
> Thank you, it successes, But the link sent to the target doesn't work I tried to open it from chrome and firefox :/

Please record a video and send it to us for review. We have not encountered such a problem in our tests


Note: If you open the link with ngrok in the above browsers, note that this tool must be run on the https platform (if it is to be uploaded on the domain that ngrok also has this mode)

**Comment by admi24** [comment]
> Storm-Breaker's initial menu options do not appear, and after clicking on the link generated by ngrok, a login screen appears asking for username and password. Was this really supposed to happen?
> 
> Img initial menu: https://drive.google.com/file/d/1H5i3fU8Z3bceXvlGPRp3kovpg7gkB7x9/view?usp=sharing Img login screen: https://drive.google.com/file/d/146IoKZWHfO1pI5al3C7Zo2kk1mxdspGh/view?usp=sharing

same issue for me...

**Comment by Git-JoaoPauloSantos** [comment]
Thanks for the tips, it worked perfectly!

**Comment by abdullah0-tech** [comment]
Hello everyone! I'm facing a huge problem while installing Storm Breaker in Kali Linux. When I provide the path for the git clone and then run it in the Kali terminal, it asks for a username and password after some time. When I enter the username 'admin' and the same password, it shows that the password was changed on August 21, 2021. Please help me find a solution to this problem.
