### ISSUE TITLE
No module named colorama 

### ISSUE THREAD

**Issue by blockcrafter21** [ultrasecurity/Storm-Breaker#34]
On google cloud shell after executing all commands in readme.md i get this error

`raceback (most recent call last):
  File "Storm-Breaker.py", line 6, in <module>
    from modules import banner
  File "/home/demet3r/Storm-Breaker/modules/banner.py", line 2, in <module>
    from colorama import Fore
ModuleNotFoundError: No module named 'colorama'`

**Comment by Faiz-Anjum** [comment]
> On google cloud shell after executing all commands in readme.md i get this error
> 
> `raceback (most recent call last): File "Storm-Breaker.py", line 6, in <module> from modules import banner File "/home/demet3r/Storm-Breaker/modules/banner.py", line 2, in <module> from colorama import Fore ModuleNotFoundError: No module named 'colorama'`

Run this code on your Python3 environment to manually install colorama

`pip3 install colorama`

**Comment by blockcrafter21** [comment]
I did but still not working

**Comment by SoggyBook** [comment]
> I did but still not working

did u figure it out

**Comment by blockcrafter21** [comment]
> > I did but still not working
> 
> 
> 
> did u figure it out
> 
> 

No i didnt
