### ISSUE TITLE
connect() got an unexpected keyword argument 'auth_token' 

### ISSUE THREAD

**Issue by ArtemusTBR** [ultrasecurity/Storm-Breaker#35]
Hello Guys I'm getting this error unexpectedly. I have installed all requirements perfectly I can run the program but as soon as I try to use for generating access link it shows this error.
![Screenshot_2021-08-20_00_00_31](https://user-images.githubusercontent.com/89236823/130177240-9f8fd865-49d5-4b67-bac4-fbe5446d3888.png)
You  can see the error in the given attachment and help me please.

**Comment by anish03Rd** [comment]
![Uploading IMG_20210912_141912.jpg…]()




Please use your ngrok token 
At auoth_token=token

**Comment by anish03Rd** [comment]
![Uploading IMG_20210912_141912.jpg…]()


Use like this

**Comment by vikashchand** [comment]
> Use like this

bro the pics u are uploading is not being downloaded or viewed,
i have an error with ngrok ,few hours before this tool was working but now its showing tunnel not found error, would u please help me in resolving this ,and one more thing that config,json file has ngrok=wewewe is it some error??
