### ISSUE TITLE
No ASCII caracter error

### ISSUE THREAD

**Issue by Termin44l** [ultrasecurity/Storm-Breaker#36]
I have this error when running sudo python Storm-Breaker.py: 
SyntaxError: Non-ASCII character '\xe2' in file Storm-Breaker.py on line 42, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

I have run install.sh and installed requirements.

Also, when I run the command sudo python3 Storm-Breaker.py, I get this error:

Traceback (most recent call last):
  File "/home/Termin44l/Tools/Storm-Breaker/Storm-Breaker.py", line 7, in <module>
    from modules import localhost
  File "/home/Termin44l/Tools/Storm-Breaker/modules/localhost.py", line 1, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'

When I wanna install it with sudo apt install pyngrok, it just fails with the unable to locate package pyngrok.

**Comment by bennetho** [comment]
sudo pip3 install pyngrok
