### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by lordokeson** [ultrasecurity/Storm-Breaker#40]
when I ran the operation to initiate the tool I get this 

 sudo python3 Storm-Breaker.py

 ` File "Storm-Breaker.py", line 7, in <module>
    from modules import localhost
  File "/home/steve/Storm-Breaker/modules/localhost.py", line 1, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok' `

**Comment by wrench008** [comment]
pip3 install pyngrok

**Comment by xploitstech** [comment]
run in  root terminal
