### ISSUE TITLE
Traceback (most recent call last):   File "Storm-Breaker.py", line 7, in <module>     from modules import localhost   File "/home/cloud/git-apps/Storm-Breaker/modules/localhost.py", line 1, in <module>     from pyngrok import ngrok ModuleNotFoundError: No module named 'pyngrok'

### ISSUE THREAD

**Issue by blockcrafter21** [ultrasecurity/Storm-Breaker#45]
OS: ubuntu server lts 20.3 
i executed the install.sh
then the other commands but still getting this error (and yes i did pip3 install pyngrok)
`Traceback (most recent call last):
  File "Storm-Breaker.py", line 7, in <module>
    from modules import localhost
  File "/home/cloud/git-apps/Storm-Breaker/modules/localhost.py", line 1, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'`

ps : can you maybe update the README.md

**Comment by bennetho** [comment]
sudo bash install.sh

sudo pip3 install pyngrok

**Comment by blockcrafter21** [comment]
i did this but still not working and you would know this if you read my issue

**Comment by blockcrafter21** [comment]
> sudo bash install.sh
> 
> sudo pip3 install pyngrok

@bennetho 
i did this but still not working and you would know this if you read my issue

**Comment by JamesQSL** [comment]
How can we update the readme.txt? Thanks
