### ISSUE TITLE
strom-breaker.by can not run 

### ISSUE THREAD

**Issue by harsh89411111** [ultrasecurity/Storm-Breaker#50]
Traceback (most recent call last):
  File "/root/tweakandtools/Storm-Breaker/Storm-Breaker.py", line 36, in <module>
    banner.banner()
  File "/root/tweakandtools/Storm-Breaker/modules/banner.py", line 10, in banner
    Popen('neofetch')
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'neofetch'

**Comment by joshkar** [comment]
> Traceback (most recent call last):
> File "/root/tweakandtools/Storm-Breaker/Storm-Breaker.py", line 36, in
> banner.banner()
> File "/root/tweakandtools/Storm-Breaker/modules/banner.py", line 10, in banner
> Popen('neofetch')
> File "/usr/lib/python3.9/subprocess.py", line 951, in **init**
> self._execute_child(args, executable, preexec_fn, close_fds,
> File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
> raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'neofetch'

Please run install.sh first and then run the tool

And that this tool is for Kali Linux
