### ISSUE TITLE
Location command is not of any use

### ISSUE THREAD

**Issue by Rachit-Pandey-2004** [ultrasecurity/Storm-Breaker#51]
The location which I received is not accurate it only shows the correct city only nothing more than that. I thought it give the accurate location of the person.

**Comment by bennetho** [comment]
Understand location use near me

**Comment by joshkar** [comment]
> The location which I received is not accurate it only shows the correct city only nothing more than that. I thought it give the accurate location of the person.

Hi. Exact location is only possible through smartphones, not personal computers

**Comment by ivano1981** [comment]
[#](https://github.com/bennetho) how to use not option one and 2

**Comment by ivano1981** [comment]
@ bennetho
