### ISSUE TITLE
ModuleNotFoundError: No Module Named 'pip' 

### ISSUE THREAD

**Issue by VaishnavPatil** [ultrasecurity/Storm-Breaker#52]
please help me to solve this problem

**Comment by BanukaKA** [comment]
Reinstall pip
Simply uninstall it and reinstall
Installation:
https://linuxconfig.org/how-to-install-pip-on-kali-linux

**Comment by VaishnavPatil** [comment]
> Reinstall pip
> Simply uninstall it and reinstall
> Installation:
> https://linuxconfig.org/how-to-install-pip-on-kali-linux
**Thank-you So For Helping Me It's Helpful For Me**

**Comment by stevengreg2020** [comment]
┌──(Kali Linus㉿kali)-[~]
└─$ git clone https://github.com/ultrasecurity/Storm-Breaker
cd Storm-Breaker
sudo bash linux-installer.sh
python3 -m pip install -r requirments.txt
sudo python3 Storm-Breaker.py
fatal: destination path 'Storm-Breaker' already exists and is not an empty directory.
[sudo] password for nexphisher:
bash: linux-installer.sh: No such file or directory
/usr/bin/python3: No module named pip
Traceback (most recent call last):
File "/home/nexphisher/Storm-Breaker/Storm-Breaker.py", line 4, in
import pip
ModuleNotFoundError: No module named 'pip'

┌──(Kali Linus㉿kali)-[~/Storm-Breaker]
└─$ git clone https://github.com/ultrasecurity/Storm-Breaker 1 ⨯
fatal: could not create work tree dir 'Storm-Breaker': Permission denied

please can someone help me out on this error how do i solve it i tried to install Storm-Breaker this is what i keep getting

**Comment by joshkar** [comment]
> ┌──(Kali Linus㉿kali)-[~]
> └─$ git clone https://github.com/ultrasecurity/Storm-Breaker
> cd Storm-Breaker
> sudo bash linux-installer.sh
> python3 -m pip install -r requirments.txt
> sudo python3 Storm-Breaker.py
> fatal: destination path 'Storm-Breaker' already exists and is not an empty directory.
> [sudo] password for nexphisher:
> bash: linux-installer.sh: No such file or directory
> /usr/bin/python3: No module named pip
> Traceback (most recent call last):
> File "/home/nexphisher/Storm-Breaker/Storm-Breaker.py", line 4, in
> import pip
> ModuleNotFoundError: No module named 'pip'
> 
> ┌──(Kali Linus㉿kali)-[~/Storm-Breaker]
> └─$ git clone https://github.com/ultrasecurity/Storm-Breaker 1 ⨯
> fatal: could not create work tree dir 'Storm-Breaker': Permission denied
> 
> please can someone help me out on this error how do i solve it i tried to install Storm-Breaker this is what i keep getting

You are in the nextphisher folder and you need to go to the Stormbreaker tool folder
cd Desktop
sudo git clone https://github.com/ultrasecurity/Storm-Breaker
cd Storm-Breaker
sudo python3 -m pip install requirments.txt
sudo python3 Storm-Breaker.py

**Comment by devallsaint** [comment]
help me
└─$ sudo python3 Storm-Breaker.py
Traceback (most recent call last):
  File "/home/andrei/Desktop/Storm-Breaker/Storm-Breaker.py", line 7, in <module>
    from modules import localhost
  File "/home/andrei/Desktop/Storm-Breaker/modules/localhost.py", line 1, in <module>
    from pyngrok import ngrok

**Comment by monstermo14** [comment]
just do apt install pip
