### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by AryanNareda** [ultrasecurity/Storm-Breaker#54]
i am trying to type bit clone https://github.com/ultrasecurity/Storm-Breaker.git 
but its not instalklling written failure

**Comment by AryanNareda** [comment]
please tell

**Comment by joshkar** [comment]
Hi. I do not understand what you mean. Can you explain your problem further?

**Comment by joshkar** [comment]
> i am trying to type bit clone https://github.com/ultrasecurity/Storm-Breaker.git
> but its not instalklling written failure

Hi. I do not understand what you mean. Can you explain your problem further?
