### ISSUE TITLE
heartbeat timeout, terminating session 

### ISSUE THREAD

**Issue by shentl168** [ultrasecurity/Storm-Breaker#57]
t=2021-09-24T22:01:46-0400 lvl=eror msg="heartbeat timeout, terminating session" obj=csess id=6bd5d92d4c84 clientid=38104d2e579069f65529c90981ada85d                                                                                       
t=2021-09-24T22:01:46-0400 lvl=eror msg="session closed, starting reconnect loop" obj=csess id=e37e06e0f0ba err="session closed"                                                                                                           
t=2021-09-24T22:02:12-0400 lvl=eror msg="heartbeat timeout, terminating session" obj=csess id=8dc4d2719c5f clientid=38104d2e579069f65529c90981ada85d                                                                                       
t=2021-09-24T22:02:12-0400 lvl=eror msg="session closed, starting reconnect loop" obj=csess id=e37e06e0f0ba err="session closed"

**Comment by rithesh6** [comment]
Could you find the solution for this ?
