### ISSUE TITLE
Mobile Camera Error

### ISSUE THREAD

**Issue by LAzyFrAAnk** [ultrasecurity/Storm-Breaker#59]
I get the below error when I chose mobile camera

t=2021-09-28T17:19:33-0400 lvl=warn msg="can't bind default web address, trying alternatives" obj=web addr=127.0.0.1:4040

**Comment by theEndurance-del** [comment]
> linux os

Can you provide your `/etc/hosts` file?

**Comment by theEndurance-del** [comment]
> Can you provide your `/etc/hosts` file?

Since this error is not actually related to the tool what you are using but your actual network configuration(the error is in fact generated by ngrok), Please make sure that your `/etc/hosts` looks like this:

```
127.0.0.1    localhost
::1          localhost
127.0.1.1    <your hostname>
```

**Comment by 36KnowledgeBrim** [comment]
I'm having problems with Storm-Breaker, the mobile webcam works when my target opens the link, when I go into the storm-breaker folder I can't find the images that were sent, matter fact the webcam folder in the storm-breaker directory says it's empty,I even went into the Images folder, it also says it's empty. someone plzz help me

**Comment by Warhammar** [comment]
Cant also get the link clean running: 
t=2022-01-31T13:00:55-0500 lvl=warn msg="can't bind default web address, trying alternatives" obj=web addr=127.0.0.1:4040

**Comment by Rahulchintu05** [comment]
> > Can you provide your `/etc/hosts` file?
> 
> Since this error is not actually related to the tool what you are using but your actual network configuration(the error is in fact generated by ngrok), Please make sure that your `/etc/hosts` looks like this:
> 
> ```
> 127.0.0.1    localhost
> ::1          localhost
> 127.0.1.1    <your hostname>
> ```

After this what we need to do
