### ISSUE TITLE
ModuleNotFoundError: No module named 'colorama'

### ISSUE THREAD

**Issue by HarshCodesYT** [ultrasecurity/Storm-Breaker#61]
sudo python3 Storm-Breaker.py
Traceback (most recent call last):
  File "/home/user/Storm-Breaker/Storm-Breaker.py", line 6, in <module>
    from modules import banner
  File "/home/user/Storm-Breaker/modules/banner.py", line 2, in <module>
    from colorama import Fore
ModuleNotFoundError: No module named 'colorama'

**Comment by vikashchand** [comment]
hey bro uninstall the tool then proceed with these step by step.it will definitely work
$ sudo apt install python3-pip
$ git clone https://github.com/ultrasecurity/Storm-Breaker
$ cd Storm-Breaker
$ sudo python3 -m pip install -r requirments.txt
$ sudo bash install.sh
$ sudo python3 Storm-Breaker.py

**Comment by NeroK4li778** [comment]
Same problem

**Comment by CivilSouvik** [comment]
Same problem

**Comment by NeroK4li778** [comment]
Anyone found a solution?

**Comment by sushant96702** [comment]
same prob

**Comment by JamesQSL** [comment]
Can any expert advise on this? I also facing the same issue

**Comment by Rosee-xx** [comment]
pip3 install colorama

its just a package for terminal colours
