### ISSUE TITLE
No such file or directory: 'neofetch'

### ISSUE THREAD

**Issue by TrueeZ** [ultrasecurity/Storm-Breaker#62]
Traceback (most recent call last):
  File "/home/kali/Storm-Breaker/Storm-Breaker.py", line 36, in <module>
    banner.banner()
  File "/home/kali/Storm-Breaker/modules/banner.py", line 10, in banner
    Popen('neofetch')
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'neofetch'

**Comment by firnanda-cloud** [comment]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package neofetch

i have that problem when 'sudo apt update && sudo apt install neofetch'

**Comment by Somadonna** [comment]
> You need to install neofetch. `sudo apt update && sudo apt install neofetch`

this worked 100%..thanks for this

**Comment by oendark003** [comment]
root@darkoen:~/Desktop/Storm-Breaker# sudo apt update && sudo apt install neofetch
Ign:1 https://http.kali.org/kali kali-rolling InRelease
**Err:2 https://http.kali.org/kali kali-rolling Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not** handshake: Error in the certificate verification. [IP: 192.99.200.113 443]
Reading package lists... Done                   
E: The repository 'https://http.kali.org/kali kali-rolling Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@darkoen:~/Desktop/Storm-Breaker#

**Comment by oendark003** [comment]
> You need to install neofetch. `sudo apt update && sudo apt install neofetch`

root@darkoen:~/Desktop/Storm-Breaker# sudo apt update && sudo apt install neofetch
Ign:1 https://http.kali.org/kali kali-rolling InRelease
Err:2 https://http.kali.org/kali kali-rolling Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 192.99.200.113 443]
Reading package lists... Done                   
E: The repository 'https://http.kali.org/kali kali-rolling Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@darkoen:~/Desktop/Storm-Breaker#

**Comment by oendark003** [comment]
> You need to install neofetch. `sudo apt update && sudo apt install neofetch`

Err:2 https://http.kali.org/kali kali-rolling Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification.

**Comment by angborokq1w2e3r4** [comment]
sudo apt update && sudo apt install neofetch                        1 ⨯ 1 ⚙
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package neofetch
I am having same problem plz anyone help me

**Comment by LOVE143YOU** [comment]
(kali㉿kali)-[~/Storm-Breaker]
└─$ sudo apt install nofetch
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package nofetch

can any tell me how to slove this problem

**Comment by hemant12ku** [comment]
My link is not working why?
                                                                                                                            
..............                                     root@windows                                                                                                        
            ..,;:ccc,.                             ------------                                                                                                        
          ......''';lxO.                           OS: Kali GNU/Linux Rolling x86_64                                                                                   
.....''''..........,:ld;                           Host: VMware Virtual Platform None                                                                                  
           .';;;:::;,,.x,                          Kernel: 5.10.0-kali9-amd64                                                                                          
      ..'''.            0Xxoc:,.  ...              Uptime: 1 day, 21 hours, 39 mins                                                                                    
  ....                ,ONkc;,;cokOdc',.            Packages: 2310 (dpkg)                                                                                               
 .                   OMo           ':ddo.          Shell: zsh 5.8.1                                                                                                    
                    dMc               :OO;         Resolution: 1360x612                                                                                                
                    0M.                 .:o.       WM: Xfwm4                                                                                                           
                    ;Wd                            Theme: Kali-Dark [GTK2/3]                                                                                           
                     ;XO,                          Icons: Flat-Remix-Blue-Dark [GTK2/3]                                                                                
                       ,d0Odlc;,..                 Terminal: x-terminal-emul                                                                                           
                           ..',;:cdOOd::,.         CPU: Intel i5-4210U (4) @ 1.696GHz                                                                                  
                                    .:d;.':;.      GPU: 00:0f.0 VMware SVGA II Adapter                                                                                 
                                       'd,  .'     Memory: 989MiB / 1975MiB                                                                                            
                                         ;l   ..                                                                                                                       
                                          .o                                                                                                                           
                                            c                                                                                                                          
                                            .'                                                                                                                         
                                             .                                                                                                                         
                                                                                                                                                                       
 [+] https://75e3-171-76-237-38.ngrok.io -> https://localhost:4545

**Comment by Skye12345-Emma** [comment]
(base) Skye:~ macbookpro$ sudo apt install neofetch
Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk1.8.0_321.jdk/Contents/Home/bin/apt" (-1), I got that after everything?

**Comment by syedfardin83** [comment]
type the following commands and it will be surely fixed:
$sudo apt install pip3-wheel
$pip install neofetch

**Comment by Rosee-xx** [comment]
sudo apt-get install neofetch 
simple

now you can type neofetch an look at ur specs aswell wowskiii
