### ISSUE TITLE
ModuleNotFoundError: No module named 'pyngrok'

### ISSUE THREAD

**Issue by ubback2** [ultrasecurity/Storm-Breaker#64]
sudo python3 Storm-Breaker.py                 
Traceback (most recent call last):
  File "/home/kali/Storm-Breaker/Storm-Breaker.py", line 7, in <module>
    from modules import localhost
  File "/home/kali/Storm-Breaker/modules/localhost.py", line 1, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'

**Comment by IliasOtaku** [comment]
Download pyngrok look for its commands

**Comment by nightrider454** [comment]
@IliasOtaku can you please explain briefly , thanks

**Comment by MikeResearcher** [comment]
┌──(xxxx㉿kalidude)-[~/Storm-Breaker]
└─$ sudo python3 Storm-Breaker.py
Traceback (most recent call last):
  File "/home/kalidude/Storm-Breaker/Storm-Breaker.py", line 7, in <module>
    from modules import localhost
  File "/home/kalidude/Storm-Breaker/modules/localhost.py", line 1, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'
                                                                                                                                                     
┌──(xxxx㉿kalidude)-[~/Storm-Breaker]
└─$ pip3 install pyngrok                                                                                                                         1 ⨯
Requirement already satisfied: pyngrok in /home/kalidude/.local/lib/python3.9/site-packages (5.1.0)
Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from pyngrok) (5.4.1)
                                                                                                                                                     
┌──(xxxx㉿kalidude)-[~/Storm-Breaker]
└─$ sudo python3 Storm-Breaker.py
Traceback (most recent call last):
  File "/home/kalidude/Storm-Breaker/Storm-Breaker.py", line 7, in <module>
    from modules import localhost
  File "/home/kalidude/Storm-Breaker/modules/localhost.py", line 1, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'

Same thing the others are reporting. Searched different sites and same error occurs with the recommended fixes. Thanks

**Comment by MikeResearcher** [comment]
See issue #19.  I had the same issue you have and I followed the reply in issue #19.  Cheers

**Comment by AzizBardi** [comment]
I solved the problem by typing this command :
sudo pip3 install -r requirments.txt

**Comment by JustinH71** [comment]
pip3 install pyngrok

**Comment by mari1179** [comment]
I have already installed pyngrok 
now also it showing the same error message
