### ISSUE TITLE
Error while installing requirements.txt

### ISSUE THREAD

**Issue by yhoungdev** [ultrasecurity/Storm-Breaker#65]
it throws an error while installing requirements.txt 
pyngrok is the issue

ile "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run

**Comment by nNEWBE** [comment]
![IMG_20230630_165750.jpg](https://github.com/ultrasecurity/Storm-Breaker/assets/129304376/7ea80a1a-3494-4c0c-a5db-5aa7ff8b9cfd)

How to solve this error plz tell me I stack here for 2 days 🥹

**Comment by manohar4567** [comment]
Sir how to silve this problem sir

**Comment by Johanns-alt** [comment]
HOW CAN I FIX IT, PLEASE
