### ISSUE TITLE
linux-installer.sh not found

### ISSUE THREAD

**Issue by Infir658** [ultrasecurity/Storm-Breaker#74]
![Snímek obrazovky 2021-11-02 215810](https://user-images.githubusercontent.com/72007908/139950649-7599344c-48e5-497e-a1f4-d676fee284cb.png)

Hi i can´t find linux-install.sh anywhere. Can you help ?

**Comment by Stealthzer** [comment]
I am getting the same problem as well, if anyone finds a fix to this issue please post it here as it would be very helpful.
error: linux-installer.sh: No such file or directory
picture of issue: 
![image](https://user-images.githubusercontent.com/86288550/142225365-663c5323-d8ce-4ef0-bb74-83cb42bff07c.png)

**Comment by Stealthzer** [comment]
I figured out the answer!
use the command **chmod +x install.sh** instead of linux-installer.sh

**Comment by monstermo14** [comment]
chmod +x is not needed instead you need to use bash install.sh

**Comment by cyberangel1** [comment]
> chmod +x is not needed instead you need to use bash install.sh

this worked for me while chmod +x wasn't working

**Comment by Timmyraysmom** [comment]
sudo bash install.sh worked

**Comment by xgxg22684** [comment]
ولكن عند استخدام هذا الامر sudo bash install.sh تظهر رسالة Try: sudo apt install <deb name>

**Comment by honestlytried** [comment]
Hey guys
