### ISSUE TITLE
Issue on webcam and microphone access.

### ISSUE THREAD

**Issue by Jas-Grace** [ultrasecurity/Storm-Breaker#78]
Hey guys, for me the access webcam and microphone are not working. When I generate a link for accessing webcam, and open it, nothing appears and nothing happens in the terminal also. When I try the access microphone, I get 'redirect to website' on opening the link. Please help.

**Comment by NTheOne2018** [comment]
i have the same issue, i get redirected to a website where i have to sign in to ngrok

**Comment by Alia-2015** [comment]
> i have the same issue, i get redirected to a website where i have to sign in to ngrok

same issue

**Comment by NTheOne2018** [comment]
> > i have the same issue, i get redirected to a website where i have to sign in to ngrok
> 
> same issue

i got the fix to that solution. sign into ngrok and go to "get started" (top right of the screen). Copy your authtoken. cd into Stormbreaker and write "sudo su" that way you get root access. Then write ./ngrok authoken (paste your authtoken).
