### ISSUE TITLE
a = ngrok.connect(4545,"http",authtoken=token)

### ISSUE THREAD

**Issue by Jaysathe** [ultrasecurity/Storm-Breaker#84]
Traceback (most recent call last):
  File "Storm-Breaker.py", line 46, in <module>
    localhost.webcham()
  File "/home/jaysathe/Desktop/Storm-Breaker/modules/localhost.py", line 74, in webcham
    a = ngrok.connect(4545,"http",authtoken=token)
TypeError: connect() got an unexpected keyword argument 'authtoken'

**Comment by wradhwan** [comment]
same with me,do u find solution?

**Comment by Jaysathe** [comment]
No I did Not find The Solution

**Comment by anggrei** [comment]
- [ ] 
![Slide1](https://user-images.githubusercontent.com/86122751/146041819-82a02027-1329-4e81-af90-5ead74ef4415.JPG)

 how to solve this?

**Comment by Jaysathe** [comment]
You Are Done Now..... Just Copy the Link And Sent to the Victim

**Comment by abdallashalaby** [comment]
> * [ ]
>   ![Slide1](https://user-images.githubusercontent.com/86122751/146041819-82a02027-1329-4e81-af90-5ead74ef4415.JPG)
> 
> how to solve this?

I have the same error and I can't solve it yet
