### ISSUE TITLE
link is working as something else

### ISSUE THREAD

**Issue by NTheOne2018** [ultrasecurity/Storm-Breaker#87]
i tried to use the link on myself, but instead of accessing my webcam, it puts me on a page where i need to sign up or sign in for ngrok, doesnt matter who opened the lnk. it worked the other but isnt working now, tried to uninstall it and clone it again, still not working. i need help please

**Comment by JustinH71** [comment]
Create an account at Ngrok.com. Once you've created your account click on getting started on the left side of the screen.
You'll see a link called Your Authtoken. Click on that link and use the token on top with only letter and numbers. Open up 
StormBreaker. Cd into Storm-Breaker
─$ cd Storm-Breaker. Get root access by typing sudo su. Once you have root type ngrok and paste your token number and hit enter. It should tell you that your token was saved. Then run Storm-Breaker. 
Don't use ./ngrok authtoken 22342322..ect

**Comment by NTheOne2018** [comment]
> Create an account at Ngrok.com. Once you've created your account click on getting started on the left side of the screen. You'll see a link called Your Authtoken. Click on that link and use the token on top with only letter and numbers. Open up StormBreaker. Cd into Storm-Breaker ─$ cd Storm-Breaker. Get root access by typing sudo su. Once you have root type ngrok and paste your token number and hit enter. It should tell you that your token was saved. Then run Storm-Breaker. Don't use ./ngrok authtoken 22342322..ect

i found my authtoken, but there are also symbols in it. and i tried to use the command you told me to use but it didnt work. i tried also the one it told me to do and didnt work as well

**Comment by NTheOne2018** [comment]
> Create an account at Ngrok.com. Once you've created your account click on getting started on the left side of the screen. You'll see a link called Your Authtoken. Click on that link and use the token on top with only letter and numbers. Open up StormBreaker. Cd into Storm-Breaker ─$ cd Storm-Breaker. Get root access by typing sudo su. Once you have root type ngrok and paste your token number and hit enter. It should tell you that your token was saved. Then run Storm-Breaker. Don't use ./ngrok authtoken 22342322..ect

thank you, it works now!

**Comment by hackNcode** [comment]
> Create an account at Ngrok.com. Once you've created your account click on getting started on the left side of the screen. You'll see a link called Your Authtoken. Click on that link and use the token on top with only letter and numbers. Open up StormBreaker. Cd into Storm-Breaker ─$ cd Storm-Breaker. Get root access by typing sudo su. Once you have root type ngrok and paste your token number and hit enter. It should tell you that your token was saved. Then run Storm-Breaker. Don't use ./ngrok authtoken 22342322..ect

How Do You Save it without the file

**Comment by Lusfer666** [comment]
I am trying storm-breaker link with camera and it doesn't work,
when I try to past it some were else its the same as always,
when I try to send to my Friend to check it doesn't convert to link.
Anyone can help here??
Thanks

**Comment by Mohack-max** [comment]
You have to try to make your liink short. There are some websites for that like link shortener and after try to use on your phone . I think it will work ..
