### ISSUE TITLE
the mjority of people have the same problem

### ISSUE THREAD

**Issue by an45-fgm** [ultrasecurity/Storm-Breaker#88]
i tried to use the link on myself, but instead of accessing my webcam, it puts me on a page where i need to sign up or sign in for ngrok, doesnt matter who opened the lnk. it worked the other but isnt working now, tried to uninstall it and clone it again, still not working. i need help please

**Comment by mdduan91** [comment]
same goes to me. i've been using the script in social engineering topic for my student. Been using it for a while but today its redirect me to sign up page as mentioned above. now i just demonstrate on setoolkit only. wish this problem gone sooner.

**Comment by JustinH71** [comment]
Create an account at Ngrok.com. Once you've created your account click on getting started on the left side of the screen.
You'll see a link called Your Authtoken. Click on that link and use the token on top with only letter and numbers. Open up 
StormBreaker. Cd into Storm-Breaker
─$ cd Storm-Breaker. Get root access by typing sudo su. Once you have root type ngrok and paste your token number and hit enter.
It should tell you that your token was saved. Then run Storm-Breaker. 
 Don't use ./ngrok authtoken 22342322..ect

**Comment by Fix2217** [comment]
> Create an account at Ngrok.com. Once you've created your account click on getting started on the left side of the screen. You'll see a link called Your Authtoken. Click on that link and use the token on top with only letter and numbers. Open up StormBreaker. Cd into Storm-Breaker ─$ cd Storm-Breaker. Get root access by typing sudo su. Once you have root type ngrok and paste your token number and hit enter. It should tell you that your token was saved. Then run Storm-Breaker. Don't use ./ngrok authtoken 22342322..ect


I tried it but I get : ERROR:  Unrecognized command: 22b6yb67lk...
Also I already used the ./ngrok authtoken 234543... and I tried to change the authtoken in the settings after launching storm-breaker, so maybe I broke something?
Can someone help me please?

**Comment by JustinH71** [comment]
Did you type ngrok 2347363746373etc.. If you still can't get it to work log into your ngrok account and change the token again and repeat the steps. Have you tried downloading the ngrok program from Kali into an folder unzip it and run the program. This will save your token in a file path. You can also choose settings in StormBreaker and paste your token. 3354566454ect...

**Comment by Fix2217** [comment]
Done, but it still doesnt work. The link I get contains an ip adress (and it's not supposed to) + when i open the link i get a blank page. Any other idea?

**Comment by s-kaito77** [comment]
It works for me.. can you provide an image for what u got?

**Comment by Fix2217** [comment]
[+] https://a21b-92-184-***-***.ngrok.io -> https://localhost:4545      
                                                                         
 [+] Please Send Link To Target                                          

Thats what I get if I select 1 every time (i replaced some numbers with *)
