### ISSUE TITLE
E: unable to locate package neofetch

### ISSUE THREAD

**Issue by sagimelman** [ultrasecurity/Storm-Breaker#90]
![16392596517857162204406572954103](https://user-images.githubusercontent.com/94141365/145692767-e2b865d6-f30e-442e-98d3-06fe2a650793.jpg)
I've been trying everything and it's not working. Any suggestions

**Comment by Newtoxton** [comment]
Try this url: https://www.atechtown.com/neofetch-for-ubuntu/ this will resolve your issue or else:
run: "sudo apt update"
Then:  "sudo apt install neofetch" And there you got self a fix

**Comment by QuanQuan-CHO** [comment]
> Try this url: https://www.atechtown.com/neofetch-for-ubuntu/ this will resolve your issue or else: run: "sudo apt update" Then: "sudo apt install neofetch" And there you got self a fix

It works! thanks a lot

**Comment by Franek211** [comment]
this link is not working

**Comment by liqwang** [comment]
> this link is not working

Use this archive link: https://web.archive.org/web/20211119235622/https://www.atechtown.com/neofetch-for-ubuntu/

**Comment by anandk-29** [comment]
<img width="899" height="363" alt="Image" src="https://github.com/user-attachments/assets/5646d59b-bea2-402a-affe-346bd374a062" /> it shows like this

**Comment by anandk-29** [comment]
Ah, you're using Kali Linux, not Ubuntu .
The "Unable to locate package neofetch" error on Kali typically means either:

Your package list is outdated (but you already ran sudo apt update).

neofetch isn’t available in your current repositories (which is odd but possible).

✅ Try this alternative Kali-specific solution:
Run:
sudo apt install neofetch -y --allow-unauthenticated

If that still doesn’t work:

🔁 Install Neofetch via GitHub (universal method)

Install Git if not already:
sudo apt install git

Clone Neofetch:
git clone https://github.com/dylanaraps/neofetch.git

Move into the folder:
cd neofetch

Install:
sudo make install

Run it:
neofetch

**Comment by nNEWBE** [comment]
> Ah, you're using Kali Linux, not Ubuntu . The "Unable to locate package neofetch" error on Kali typically means either:
> 
> Your package list is outdated (but you already ran sudo apt update).
> 
> neofetch isn’t available in your current repositories (which is odd but possible).
> 
> ✅ Try this alternative Kali-specific solution: Run: sudo apt install neofetch -y --allow-unauthenticated
> 
> If that still doesn’t work:
> 
> 🔁 Install Neofetch via GitHub (universal method)
> 
> Install Git if not already: sudo apt install git
> 
> Clone Neofetch: git clone https://github.com/dylanaraps/neofetch.git
> 
> Move into the folder: cd neofetch
> 
> Install: sudo make install
> 
> Run it: neofetch

It works completely after wasting hours I found the solution thanks man 💖

**Comment by madox2020** [comment]
it run: neofetch nut but it does not list out the options to choose pls i solution to for it

**Comment by dariusfrusina2018-arch** [comment]
Still.

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/043a257e-d598-4f3a-88aa-7d695b74b600" />

 Doesn't work.
