### ISSUE TITLE
Python script is a dud:  ModuleNotFoundError: No module named 'colorama'

### ISSUE THREAD

**Issue by dedev-sys** [ultrasecurity/Storm-Breaker#93]
Traceback (most recent call last):
  File "/home/dedev/Storm-Breaker/Storm-Breaker.py", line 6, in <module>
    from modules import banner
  File "/home/dedev/Storm-Breaker/modules/banner.py", line 2, in <module>
    from colorama import Fore
ModuleNotFoundError: No module named 'colorama'

**Comment by dhanushkkarh** [comment]
pip3 install -r requirements.txt

if you cant do it, whatsapp me. +916380552921

**Comment by sypherdark** [comment]
i'm having the same issue . I tried everything and nothing is working

**Comment by prashilthul** [comment]
hey mate all this error is just caused by one spelling error as the file named is requirments.txt and the command we are writing is requirements.txt so i guess if you just write pip3 install -r requirments.txt then it would work............

**Comment by wos22** [comment]
how can i fix this?, it wont let me open the sudo python3 storm-breaker.py, someone  --help?

**Comment by wos22** [comment]
bash install.sh, run this as a root! --
help?
