### ISSUE TITLE
install.sh: command not found

### ISSUE THREAD

**Issue by bardock069** [ultrasecurity/Storm-Breaker#95]
im not able to install it in storm-breaker
Plz help me

**Comment by djbugs** [comment]
How is this an issue.   Commands belong to the intelligence.  And in AI -
humans are simple the A, for assholes.

**Comment by monstermo14** [comment]
that will not work instead use sudo bash install.sh

**Comment by JMichael55** [comment]
instead of sudo bash linux-installer.sh use sudo bash  #install.sh
