### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by doggystyle333** [ultrasecurity/Storm-Breaker#97]
i really want to use this tool but i cant figure out how to get it to work, i know its probably somthing simple.

㉿kali)-[~/Storm-Breaker]
└─$ python3 -m pip install -r requirments.txt                                                                                                                                            1 ⨯
Collecting pyngrok
  Downloading pyngrok-5.1.0.tar.gz (745 kB)
     |████████████████████████████████| 745 kB 2.0 MB/s 
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from -r requirments.txt (line 2)) (0.4.4)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirments.txt (line 3)) (2.25.1)
Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from pyngrok->-r requirments.txt (line 1)) (5.4.1)
Building wheels for collected packages: pyngrok
  Building wheel for pyngrok (setup.py) ... done
  Created wheel for pyngrok: filename=pyngrok-5.1.0-py3-none-any.whl size=19007 sha256=6e1fee36296ffb3bf90c14413c6437f18f487b2bd8319f65768417a7ea902102
  Stored in directory: /home/windows/.cache/pip/wheels/a8/05/30/c9d9f2417546c7a7c329f5bba09e2cfba9991c030ad8bfb043
Successfully built pyngrok
Installing collected packages: pyngrok
  WARNING: The scripts ngrok and pyngrok are installed in '/home/windows/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                                                                          
Successfully installed pyngrok-5.1.0

㉿kali)-[~/Storm-Breaker]
└─$ sudo python3 Storm-Breaker.py            
Traceback (most recent call last):
  File "/home/windows/Storm-Breaker/Storm-Breaker.py", line 7, in <module>
    from modules import localhost
  File "/home/windows/Storm-Breaker/modules/localhost.py", line 1, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'

**Comment by Nikitas-dev** [comment]
Even I have getting the same issue I would say to re-install it if it does not work I have no Idea what to do then.

**Comment by sandeepjacob-20** [comment]
Even I had the same issue, I tried adding it to $PATH but it still doesn't fix the issue. Anyone had a working solution ?

**Comment by sandeepjacob-20** [comment]
There's some issue with pyngrok that was installed by running python3 -m pip install -r requirments.txt command. Instead I first ran this command, then I ran  python3 -m pip uninstall -r requirments.txt  which uninstalled pyngrok but kept the other two components (colorama and requests). Then I manually installed pyngrok using sudo pip3 install pyngrok and then I tried running sudo python3 Storm-Breaker.py and it worked !!!!

**Comment by partylikeits1983** [comment]
sudo pip3 install pyngrok

**Comment by svistiik** [comment]
> There's some issue with pyngrok that was installed by running python3 -m pip install -r requirments.txt command. Instead I first ran this command, then I ran python3 -m pip uninstall -r requirments.txt which uninstalled pyngrok but kept the other two components (colorama and requests). Then I manually installed pyngrok using sudo pip3 install pyngrok and then I tried running sudo python3 Storm-Breaker.py and it worked !!!!

yes this helped thanks

**Comment by Anonymous1094795585** [comment]
> There's some issue with pyngrok that was installed by running python3 -m pip install -r requirments.txt command. Instead I first ran this command, then I ran python3 -m pip uninstall -r requirments.txt which uninstalled pyngrok but kept the other two components (colorama and requests). Then I manually installed pyngrok using sudo pip3 install pyngrok and then I tried running sudo python3 Storm-Breaker.py and it worked !!!!

THANKS IT WORKED

**Comment by Sankar143388** [comment]
call 8190014338

**Comment by s0uvik** [comment]
Traceback (most recent call last):
  File "/home/kali/Storm-Breaker/Storm-Breaker.py", line 36, in <module>
    banner.banner()
  File "/home/kali/Storm-Breaker/modules/banner.py", line 10, in banner
    Popen('neofetch')
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'neofetch'

**Comment by s0uvik** [comment]
**FileNotFoundError: [Errno 2] No such file or directory: 'neofetch'**

**Comment by Ziadkorin** [comment]
> There's some issue with pyngrok that was installed by running python3 -m pip install -r requirments.txt command. Instead I first ran this command, then I ran python3 -m pip uninstall -r requirments.txt which uninstalled pyngrok but kept the other two components (colorama and requests). Then I manually installed pyngrok using sudo pip3 install pyngrok and then I tried running sudo python3 Storm-Breaker.py and it worked !!!!

I followed what u said, it just gets into a weird loop, like it's about to work but then it comes back as an empty line.

**Comment by deeq21** [comment]
I'm having the same issue
