### ISSUE TITLE
Unable to install token ngrok

### ISSUE THREAD

**Issue by madroots** [ultrasecurity/Storm-Breaker#98]
Hello, I have seen the question about loggin in to ngrok however I am still unable to view the generated link. 

I added authtoken manually, also within Storm Breaker settings but still would not work. 
I cleared cache, re-generated token, opened port (on localhost it works fine), tried another browser but no luck.
Am I missing something?

**Comment by madroots** [comment]
sorted. syntax to run is: ngrok authtoken "actual token without quotes"

**Comment by Deeparkash** [comment]
There isn't a perfect way to install
